author:
  name: Thomas Leroy
  email: thomas.leroy.mp@gmail.com

absolute_url: https://thole.fr
permalink: /blog/:year/:month/:day/:title

markdown: kramdown
theme: minima

minima:
  social_links:
    twitter: p4zuu
    github: P4zuu

plugins:
  - jekyll-feed
  - analytics
  - disqus